### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [wildfly-security/jboss-negotiation#39]
Hi
The following lines have cryptographic API misuses. <br> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 151: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 234: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 235: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 116: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 218: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 194: API name => Cipher:Operation on object of type javax.crypto.Cipher object not completed. Expected call to <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[])>, <javax.crypto.Cipher: byte[] doFinal(byte[])>, <javax.crypto.Cipher: int doFinal(java.nio.ByteBuffer,java.nio.ByteBuffer)>, update, <javax.crypto.Cipher: byte[] doFinal(byte[],int,int)>, <javax.crypto.Cipher: int doFinal(byte[],int,int,byte[],int)><BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 254: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 205: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 150: API name => IvParameterSpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcMd5Decoder.java: Line number => 47: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 160: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 151: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 138: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 119: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 142: API name => Cipher:First parameter (with value "DES/CBC/NoPadding") should be any of {AES, Blowfish, DESede, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256, RSA}<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 117: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 254: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 103: API name => Cipher:First parameter (with value "ARCFOUR") should be any of {AES, Blowfish, DESede, PBEWithHmacSHA224AndAES_128, PBEWithHmacSHA256AndAES_128, PBEWithHmacSHA384AndAES_128, PBEWithHmacSHA512AndAES_128, PBEWithHmacSHA224AndAES_256, PBEWithHmacSHA256AndAES_256, PBEWithHmacSHA384AndAES_256, PBEWithHmacSHA512AndAES_256, RSA}<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 234: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 117: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 118: API name => IvParameterSpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 120: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 104: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 106: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcMd5Decoder.java: Line number => 56: API name => MessageDigest:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/DesCbcDecoder.java: Line number => 160: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 106: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 138: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 195: API name => IvParameterSpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 218: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 236: API name => IvParameterSpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 176: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 120: API name => Cipher:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/AesCtsHmacSha1Decoder.java: Line number => 176: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/ArcFourHmacDecoder.java: Line number => 104: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 205: API name => SecretKeySpec:<BR> File name => jboss-negotiation-common/src/main/java/org/jboss/security/negotiation/cipher/Des3CbcHmacSha1KdDecoder.java: Line number => 119: API name => Cipher:<BR>

**Comment by darranl** [comment]
For issues against JBoss Negotiation please raise an issue in the following Jira project with the component set to 'Negotiation': -

https://issues.jboss.org/browse/SECURITY

However this project is reaching the end of it's life so only essential bugs will be fixed at this point.  

The listing however appears like it could be a result from some static analysis?  It looks like a lot of context is missing in relation to the problems that are actually being reported especially as this is looking at code that is almost a decade old.
